// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZI4zc_dek5XoRCfIFMFGOzFP7mlbQhzw',
    appId: '1:403544581150:web:93e9ec43ad0f7df5073a0f',
    messagingSenderId: '403544581150',
    projectId: 'mazingira-smart',
    authDomain: 'mazingira-smart.firebaseapp.com',
    storageBucket: 'mazingira-smart.appspot.com',
    measurementId: 'G-8RTGRDW404',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWIRGXMNG5fVrs2KKVWknASvo5Y479TlU',
    appId: '1:403544581150:android:65c57cfcf86ddec4073a0f',
    messagingSenderId: '403544581150',
    projectId: 'mazingira-smart',
    storageBucket: 'mazingira-smart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAae_j4ZEBSGR5synGAkls4xltgqZWF0_c',
    appId: '1:403544581150:ios:31d76585793eae0e073a0f',
    messagingSenderId: '403544581150',
    projectId: 'mazingira-smart',
    storageBucket: 'mazingira-smart.appspot.com',
    iosClientId: '403544581150-aha9m27mq74v8j5m4v15oq9d1cm273gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazingirasmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAae_j4ZEBSGR5synGAkls4xltgqZWF0_c',
    appId: '1:403544581150:ios:635a9987b8e27090073a0f',
    messagingSenderId: '403544581150',
    projectId: 'mazingira-smart',
    storageBucket: 'mazingira-smart.appspot.com',
    iosClientId: '403544581150-cu2mfrdbl8q8b166cf96b8rf3ugccj7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazingirasmart.RunnerTests',
  );
}
